# Generated by Django 2.2.3 on 2019-11-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_merchantmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
