# Generated by Django 2.2.3 on 2019-11-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191109_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('merchant_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1.MerchantModel')),
            ],
        ),
    ]
