# Generated by Django 2.2.3 on 2019-11-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191110_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='merchant_id',
            new_name='merchant',
        ),
    ]
