# Generated by Django 2.2.3 on 2019-11-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20191110_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no',
            new_name='pro_no',
        ),
    ]
