# Generated by Django 2.2.3 on 2019-11-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20191110_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
    ]
