# Generated by Django 2.2.3 on 2019-11-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_product_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
    ]
