# Generated by Django 2.2.3 on 2019-11-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20191117_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_no',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
