# Generated by Django 2.2.3 on 2019-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20191117_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete='cascade', to='app1.MerchantModel', verbose_name='idno'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
