# Generated by Django 2.2.3 on 2019-11-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20191117_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mid',
        ),
    ]
