# Generated by Django 2.2.3 on 2019-11-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_product_mid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
