# Generated by Django 2.2.3 on 2019-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MerchantModel',
            new_name='Merchant2Model',
        ),
    ]
