# Generated by Django 2.2.3 on 2019-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20191117_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merchant2Model',
            new_name='MerchantModel',
        ),
    ]
