# Generated by Django 2.2.3 on 2019-11-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantModel',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
