# Generated by Django 2.2.3 on 2019-11-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20191117_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminModelNew',
            new_name='AdminModel',
        ),
    ]
