# Generated by Django 2.2.3 on 2019-11-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_merchantmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
