# Generated by Django 2.2.3 on 2019-11-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_customermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
