# Generated by Django 2.2.3 on 2019-11-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
