# Generated by Django 2.2.3 on 2019-11-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
